### ISSUE TITLE
Does not show up in package list

### ISSUE THREAD

**Issue by samsondav** [reasonml-editor/sublime-reason#10]
I am Sublime Text dev build 3157.

I've tried several times, the repository is definitely in my user settings but it does not show up in the list of installed packages.

**Comment by gilbert** [comment]
Same here. It was working last month...

**Comment by gilbert** [comment]
Here's a workaround:

1. Go to Sublime Text > Preferences > Browse Packages
2. `cd` into this folder (if you're on os x, you can click & drag the folder icon to your terminal window)
3. `git clone https://github.com/reasonml-editor/sublime-reason`

**Comment by bsansouci** [comment]
Same problem here.

**Comment by chenglou** [comment]
Thanks for the report. I've updated the instructions @gilbert

I've submitted the package officially to https://github.com/wbond/package_control_channel/pull/7045, but no feedback so far

**Comment by chenglou** [comment]
Plugin's merged. You should be able to get it from the official channel now!
