### ISSUE TITLE
Unable to find the package on package-control

### ISSUE THREAD

**Issue by acorrenson** [reasonml-editor/sublime-reason#15]
Hello, I'd like to install this package but i cant find it in package-control...
This is weird...

<img width="583" alt="image" src="https://user-images.githubusercontent.com/16467095/57974978-55fffe80-79c1-11e9-8f19-65647e9dbe32.png">

If someone can help me ^^.

**Comment by nalvid** [comment]
The same problem here!

**Comment by mfirry** [comment]
Same problem here. Using `Sublime Text 3.2.2, Build 3211`.

**Comment by chenglou** [comment]
Weird, this one right? https://packagecontrol.io/packages/Reason

**Comment by mfirry** [comment]
oops. looks like I already had it installed. sorry!

**Comment by acorrenson** [comment]
I found an alternative : switching to vscode x)
