### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by jeremylan** [reasonml-editor/sublime-reason#6]
Hi 

I installed the plugin today and got it to work, thanks.

I have a couple of suggestions for the documentation.

1) I would add to the 'Installation' section the explicit instruction to install the package <code>sublime-reason</code> once the repository is added. Adding the repository https://github.com/reasonml-editor/sublime-reason.git does not seem to install the package.

2) I installed the plugin to be able to edit files in this workshop:
https://github.com/bassjacob/reason-workshop
All the source files there are <code>.re</code> hence I had to add the following to the <code>Preferences: LSP Settings</code>

<pre>"scopes": ["source.reason", "source.ocaml", <b>"source.re"</b>],</pre>

Thanks

**Comment by chenglou** [comment]
Hey!

1. That should have worked? What else did you need to do afterward?

2. You shouldn't need `source.re`? Btw, I'm upstreaming the config to ST LSP, so in the future, you can remove the custom config here =)

**Comment by jeremylan** [comment]
Hi @chenglou  thanks for the reply

1. adding the repo did not install the package, I had to install it explicitly in Package Control using Install Package

2. Without source.re the syntax highlighting did not work for .re files. Good about the LSP upstream :)

Cheers

**Comment by chenglou** [comment]
Coming back to this issue. I've documented the first part afterward but I can't find anywhere in my sublime settings where I needed to set `source.re`. This is really weird...

**Comment by jeremylan** [comment]
Hi @chenglou do you mean your configuration is highlighting syntax correctly for .re files without  having to do anything? Or do you mean you cannot find where to add the config?

If the latter, what I did was:

1) Go to Tools > Command Palette
2) Select 'Preferences: LSP Settings'
3) Modify the User preferences adding <pre>source.re</pre> to the following:

<pre>
// Settings in here override those in "LSP/LSP.sublime-settings",
{
	"clients": 
	{
    	"reason": 
    	   {
      		"command": ["ocaml-language-server", "--stdio"],
      		"scopes": ["source.reason", "source.ocaml", <b>"source.re"</b>],
      		"syntaxes": ["Packages/sublime-reason/Reason.tmLanguage"],
      		"languageId": "reason"
    	   }
  	}
}
</pre>

Without this syntax highlighting for .re files did not work

Hope it helps.

**Comment by chenglou** [comment]
Right, I'm saying I didn't have to do that (after having installed sublime-reason itself). That's weird, @bsansouci did you encounter this?

**Comment by bsansouci** [comment]
No didn't need to that. I had LSP and just re-installed `sublime-reason` and I got highlighting immediately (and I have reason-cli so ocamlmerlin worked).
Without sublime-reason I had no highlighting.

**Comment by chenglou** [comment]
I've reinstalled everything and it seems that `source.re` isn't needed. Maybe it's a stale config?

1 is resolved a while ago now. Thanks for the feedback! I'll close this issue; if there are still problems, please ping me =)
