### ISSUE TITLE
Can `refmt` be called on save?

### ISSUE THREAD

**Issue by yatesco** [reasonml-editor/sublime-reason#9]
I notice vscode can be configured to call `refmt` on save, but it doesn't appear there is a way to do that on sublime.

I am a sublime newbie so this is more a "help" than a "bug" :-).

It appears trivial to create a plugin (https://stackoverflow.com/questions/42233292/sublimetext-typescript-format-on-save#42237769) but I thought I would find prior art first.

Thanks!

**Comment by chenglou** [comment]
Yes! See https://github.com/reasonml-editor/sublime-reason#bonus-language-server-configuration =)
